"use client";

import { useChat } from "@ai-sdk/react";
import { DefaultChatTransport } from "ai";
import { useEffect, useRef, useState } from "react";
import { ChatMessage } from "./chat-message";
import { ChatInput } from "./chat-input";
import { StatusBadge } from "./status-badge";
import { QuickActions } from "./quick-actions";
import { TargetSettings } from "./target-settings";
import { Shield, Terminal, AlertCircle, Settings, MessageSquare } from "lucide-react";
import { parseCommand, getHelpMessage } from "@/lib/ai/agent";
import { setTarget, getContext } from "@/lib/context/store";
import { Button } from "@/components/ui/button";
import { ChatSDKBadge } from "./chatsdk-badge";

// Helper to extract text from UIMessage parts
function getMessageText(message: { parts?: Array<{ type: string; text?: string }> }): string {
  if (!message.parts || !Array.isArray(message.parts)) return "";
  return message.parts
    .filter((p): p is { type: "text"; text: string } => p.type === "text" && typeof p.text === "string")
    .map((p) => p.text)
    .join("");
}

const WELCOME_MESSAGE = `## Welcome to BreachSense

**AI Security Agent | Running on ChatSDK (Slack + Discord ready)**

I think like an attacker to protect like an expert. I can help you:

- **Simulate attacks** with real payloads and exploit chains
- **Analyze breach impacts** and show exactly how YOU are affected
- **Provide incident response** with priority actions and responsible teams

---

### Quick Start

| Command | Description |
|---------|-------------|
| \`/target <url>\` | Set your target application |
| \`/break\` | Simulate attack on target |
| \`/impact <incident>\` | Analyze breach impact on YOUR system |
| \`/breach <type>\` | Get incident response plan |

---

**Default Target:** OWASP Juice Shop (a known vulnerable application)

Try \`/break\` now to see a detailed attack simulation!

---

*This response was generated by BreachSense running across ChatSDK platforms (Slack + Discord ready).*`;

export function ChatInterface() {
  const messagesEndRef = useRef<HTMLDivElement>(null);
  const [showSettings, setShowSettings] = useState(false);
  const [currentTarget, setCurrentTarget] = useState(getContext().target);
  
  // Local messages for commands handled client-side (like /target, /help)
  const [localMessages, setLocalMessages] = useState<Array<{
    id: string;
    role: "user" | "assistant";
    content: string;
  }>>([
    {
      id: "welcome",
      role: "assistant",
      content: WELCOME_MESSAGE,
    },
  ]);

  const { messages, sendMessage, status } = useChat({
    transport: new DefaultChatTransport({ api: "/api/chat" }),
  });

  const isLoading = status === "streaming" || status === "submitted";

  // Auto-scroll to bottom on new messages
  useEffect(() => {
    messagesEndRef.current?.scrollIntoView({ behavior: "smooth" });
  }, [messages, localMessages, isLoading]);

  // Transform useChat messages to display format
  const apiMessages = messages.map((msg) => ({
    id: msg.id,
    role: msg.role as "user" | "assistant",
    content: getMessageText(msg),
  }));

  // Combine local and API messages
  const allMessages = [...localMessages, ...apiMessages];

  const handleSubmit = async (message: string) => {
    const command = parseCommand(message);
    
    // Handle /target command locally for immediate feedback
    if (command.type === "target" && command.url) {
      const updatedContext = setTarget("default", command.url);
      setCurrentTarget(updatedContext.target);
      
      setLocalMessages(prev => [
        ...prev,
        {
          id: `user-${Date.now()}`,
          role: "user" as const,
          content: message,
        },
        {
          id: `assistant-${Date.now()}`,
          role: "assistant" as const,
          content: `**Target Registered Successfully**

**URL:** ${updatedContext.target}
**Detected Type:** ${updatedContext.type === "web" ? "Web Application" : "API Endpoint"}
**Environment:** ${updatedContext.environment}

You can now use \`/break\` to simulate an attack on this target.`,
        },
      ]);
      return;
    }
    
    // Handle /help command locally
    if (command.type === "help") {
      setLocalMessages(prev => [
        ...prev,
        {
          id: `user-${Date.now()}`,
          role: "user" as const,
          content: message,
        },
        {
          id: `assistant-${Date.now()}`,
          role: "assistant" as const,
          content: getHelpMessage(),
        },
      ]);
      return;
    }
    
    // For other commands (/break, /impact, /breach), send to API
    // The useChat hook handles adding the user message to the messages array
    sendMessage({ text: message });
  };

  const handleTargetChange = (newTarget: string) => {
    const updatedContext = setTarget("default", newTarget);
    setCurrentTarget(updatedContext.target);
    
    setLocalMessages(prev => [
      ...prev,
      {
        id: `assistant-${Date.now()}`,
        role: "assistant" as const,
        content: `**Target Updated**

**URL:** ${updatedContext.target}
**Detected Type:** ${updatedContext.type === "web" ? "Web Application" : "API Endpoint"}
**Environment:** ${updatedContext.environment}`,
      },
    ]);
    setShowSettings(false);
  };

  return (
    <div className="flex flex-col h-screen bg-background">
      {/* Header */}
      <header className="flex items-center justify-between px-4 py-3 border-b border-border bg-card">
        <div className="flex items-center gap-3">
          <div className="flex h-10 w-10 items-center justify-center rounded-lg bg-primary/10 border border-primary/20">
            <Shield className="h-5 w-5 text-primary" />
          </div>
          <div>
            <h1 className="text-lg font-semibold text-foreground">BreachSense</h1>
            <div className="flex items-center gap-2">
              <p className="text-xs text-muted-foreground">AI Security Agent</p>
              <span className="text-muted-foreground/50">|</span>
              <div className="flex items-center gap-1 text-xs text-primary">
                <MessageSquare className="h-3 w-3" />
                <span>ChatSDK</span>
              </div>
            </div>
          </div>
        </div>
        <div className="flex items-center gap-2">
          <ChatSDKBadge variant="compact" className="hidden sm:flex" />
          <Button
            variant="ghost"
            size="icon"
            onClick={() => setShowSettings(!showSettings)}
            className="text-muted-foreground hover:text-foreground"
          >
            <Settings className="h-5 w-5" />
          </Button>
          <StatusBadge status="demo" platform="web" />
        </div>
      </header>

      {/* Settings Panel */}
      {showSettings && (
        <TargetSettings
          currentTarget={currentTarget}
          onTargetChange={handleTargetChange}
          onClose={() => setShowSettings(false)}
        />
      )}

      {/* Target Context Banner */}
      <div className="flex items-center gap-2 px-4 py-2 bg-secondary/30 border-b border-border">
        <Terminal className="h-4 w-4 text-muted-foreground" />
        <span className="text-xs text-muted-foreground">
          Current target:{" "}
          <code className="text-primary">{currentTarget}</code>
        </span>
      </div>

      {/* Messages */}
      <div className="flex-1 overflow-y-auto p-4">
        <div className="max-w-3xl mx-auto space-y-4">
          {allMessages.map((message) => (
            <ChatMessage
              key={message.id}
              role={message.role}
              content={message.content}
              isStreaming={
                isLoading && 
                message.id === allMessages[allMessages.length - 1]?.id && 
                message.role === "assistant"
              }
            />
          ))}
          
          {/* Loading indicator when waiting for response */}
          {isLoading && (
            apiMessages.length === 0 || 
            apiMessages[apiMessages.length - 1]?.role === "user"
          ) && (
            <div className="flex items-center gap-2 text-muted-foreground p-4">
              <div className="flex space-x-1">
                <div className="w-2 h-2 bg-primary rounded-full animate-bounce" style={{ animationDelay: "0ms" }} />
                <div className="w-2 h-2 bg-primary rounded-full animate-bounce" style={{ animationDelay: "150ms" }} />
                <div className="w-2 h-2 bg-primary rounded-full animate-bounce" style={{ animationDelay: "300ms" }} />
              </div>
              <span className="text-sm">Analyzing...</span>
            </div>
          )}

          {status === "error" && (
            <div className="flex items-center gap-2 p-4 bg-destructive/10 border border-destructive/20 rounded-lg text-destructive">
              <AlertCircle className="h-4 w-4" />
              <span className="text-sm">An error occurred. Please try again.</span>
            </div>
          )}
          <div ref={messagesEndRef} />
        </div>
      </div>

      {/* Input */}
      <div className="border-t border-border p-4 bg-card">
        <div className="max-w-3xl mx-auto space-y-3">
          {allMessages.length <= 1 && (
            <div className="pb-2">
              <p className="text-xs text-muted-foreground mb-2">Quick actions:</p>
              <QuickActions onAction={handleSubmit} disabled={isLoading} />
            </div>
          )}
          <ChatInput onSubmit={handleSubmit} isLoading={isLoading} />
        </div>
      </div>
    </div>
  );
}
