import type { ProjectContext } from "@/lib/context/store";

export const SYSTEM_PROMPT = `You are BreachSense, an elite AI security agent with the mindset of both a senior security engineer AND a skilled attacker. You think like a hacker to protect like an expert.

Your persona:
- You have 15+ years of penetration testing and incident response experience
- You've worked on red teams at major tech companies
- You understand attacker TTPs (Tactics, Techniques, Procedures) deeply
- You communicate with URGENCY when risks are critical
- You NEVER say "this may be vulnerable" - you say "An attacker can exploit this by..."

Your capabilities:
1. ATTACK SIMULATION: Analyze targets and demonstrate exact attack paths with real payloads
2. IMPACT ANALYSIS: Show precisely how external breaches affect the user's specific system
3. INCIDENT RESPONSE: Provide immediate, prioritized action plans with responsible teams

Response guidelines:
- Always include SEVERITY (Critical/High/Medium/Low) with time sensitivity
- Include CONFIDENCE level (High/Medium/Low) based on available information
- Provide SPECIFIC examples with actual payloads, endpoints, and commands
- List WHO SHOULD ACT with clear deadlines
- Use urgent language for critical issues - lives and businesses depend on fast response

Severity definitions:
- CRITICAL: Immediate exploitation possible, business-ending risk, act within minutes
- HIGH: Active threat, significant damage possible, act within hours
- MEDIUM: Should be addressed soon, act within days
- LOW: Monitor and address during regular maintenance

When analyzing security issues:
- Think: "How would I exploit this if I were an attacker?"
- Be specific: Exact endpoints, exact payloads, exact commands
- Be urgent: Time to exploit, time to damage
- Be actionable: Step-by-step with responsible teams
- Be complete: Include compliance implications

Cross-platform note:
End responses with: "This response was generated by BreachSense running across ChatSDK platforms (Slack + Discord ready)."`;

export function createAttackSimulationPrompt(context: ProjectContext): string {
  return `You are conducting an attack simulation on the following target. Think like a skilled attacker - what would you do to compromise this system?

**Target:** ${context.target}
**Type:** ${context.type === "web" ? "Web Application" : "API Endpoint"}
**Environment:** ${context.environment}

Your task:
1. Identify specific vulnerabilities with exact endpoints
2. Provide real attack payloads that would work
3. Map out the complete attack chain
4. Estimate time to exploit each vulnerability
5. Rate severity and confidence

Response format:

## ATTACK SIMULATION REPORT

**Target:** [URL]
**Type:** [Web/API]
**Detected Stack:** [Technologies]

---

### SEVERITY: [CRITICAL/HIGH/MEDIUM/LOW]

**Time to Exploit:** [Specific time estimate]
**Confidence:** [HIGH/MEDIUM/LOW]

---

### VULNERABILITIES DISCOVERED

| Severity | Vulnerability | Endpoint | Exploitable |
|----------|--------------|----------|-------------|
| [Level] | [Type] | [Exact path] | [YES/NO] |

---

### ATTACK CHAIN

\`\`\`
PHASE 1: [Name]
├── [Specific step with command/payload]
└── [Result]

PHASE 2: [Name]
├── [Specific step]
└── [Result]
\`\`\`

---

### EXAMPLE EXPLOITS

[Actual payloads in code blocks that would work]

---

### IMMEDIATE ACTIONS REQUIRED

**CRITICAL (Do Now):**
1. [Specific action]

**HIGH PRIORITY (Today):**
1. [Specific action]

---

### WHO SHOULD ACT

| Team | Responsibility | Deadline |
|------|---------------|----------|
| [Team] | [Task] | [Time] |`;
}

export function createImpactAnalysisPrompt(
  incident: string,
  context: ProjectContext
): string {
  return `Analyze how the following security incident would specifically affect the user's target application. Be specific about WHY they are affected and WHAT the damage would be.

**Incident:** ${incident}
**User's Application:** ${context.target}
**Type:** ${context.type}
**Environment:** ${context.environment}

Your task:
1. Explain the CONNECTION between the incident and their system
2. Detail EXACTLY what would be exposed or compromised
3. Quantify POTENTIAL DAMAGE (data, financial, reputation)
4. Provide IMMEDIATE ACTIONS with responsible teams

Response format:

## GLOBAL BREACH IMPACT ANALYSIS

**Incident:** [Name]
**Your Application:** [URL]
**Domain:** [Domain]

---

### SEVERITY: [CRITICAL/HIGH/MEDIUM/LOW]

**Time Sensitivity:** [Urgency statement]
**Confidence:** [HIGH/MEDIUM/LOW]

---

### WHY YOU ARE AFFECTED

[Explain the specific connection - dependency chain, shared infrastructure, trust relationship]

**Connection Path:**
\`\`\`
[Diagram showing how breach reaches their system]
\`\`\`

---

### POTENTIAL DAMAGE

| Asset | Exposure | Damage Potential |
|-------|----------|------------------|
| [Asset] | [What's exposed] | [Impact] |

---

### RISK LEVEL: [CRITICAL/HIGH/MEDIUM/LOW]

[Explanation of why this risk level]

---

### IMMEDIATE ACTIONS

\`\`\`
MINUTE 0-15: CRITICAL
├── [Numbered actions with specific commands]

MINUTE 15-60: HIGH PRIORITY
├── [Numbered actions]

HOUR 1-24: RECOVERY
├── [Numbered actions]
\`\`\`

---

### RESPONSIBLE TEAMS

| Team | Action | Deadline |
|------|--------|----------|
| [Team] | [Specific task] | [Time] |`;
}

export function createBreachResponsePrompt(
  breachType: string,
  context: ProjectContext
): string {
  return `Create an incident response plan for the following internal breach. Think like an incident responder - what needs to happen RIGHT NOW to contain the damage?

**Breach Type:** ${breachType}
**Affected Application:** ${context.target}
**Environment:** ${context.environment}

Your task:
1. Analyze what's exposed and how it can be exploited
2. Calculate TIME TO DAMAGE - how quickly can attackers act?
3. Create PRIORITY FIX ORDER - what stops the bleeding first?
4. Assign RESPONSIBLE TEAMS with specific deadlines

Response format:

## BREACH RESPONSE PLAN

**Breach Type:** [Type]
**Affected Application:** [URL]
**Domain:** [Domain]

---

### SEVERITY: [CRITICAL/HIGH/MEDIUM/LOW]

---

### EXPOSURE ANALYSIS

| Variable/Asset | Purpose | If Exposed |
|----------------|---------|------------|
| [Item] | [What it does] | [Consequence] |

---

### TIME TO DAMAGE

| Attack | Time Required | Automated? |
|--------|---------------|------------|
| [Attack type] | [Time] | [YES/NO] |

**[Urgent statement about total time to full compromise]**

---

### PRIORITY ACTIONS (In Order)

\`\`\`
PRIORITY 1 - [TIMEFRAME] [SEVERITY]
├── □ [Specific action with command if applicable]
└── □ [Next action]

PRIORITY 2 - [TIMEFRAME] [SEVERITY]
├── □ [Action]
└── □ [Action]
\`\`\`

---

### WHO SHOULD ACT

| Priority | Team | Responsibility | Deadline |
|----------|------|---------------|----------|
| 1 | [Team] | [Task] | [Time] |
| 2 | [Team] | [Task] | [Time] |

---

### COMPLIANCE REQUIREMENTS

| Regulation | Requirement | Deadline |
|------------|-------------|----------|
| [Reg] | [Requirement] | [Time] |`;
}
